name: alv

on:
  workflow_call:    
    inputs:
      environment:
        description: "Environment to notify the build and deploy"
        required: false
        type: string
        default: develop
      enableNotification:
        description: "Always true unless specified otherwise"
        required: false
        type: boolean
        default: true
  workflow_dispatch:    
    inputs:
      environment:
        description: "Environment to notify the build and deploy"
        required: false
        type: string
        default: develop
      enableNotification:
        description: "Always true unless specified otherwise"
        required: false
        type: boolean
        default: true

jobs:
  deploy_heroku_application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v2
      - if: inputs.enableNotification && (inputs.environment == 'staging')
        name: Notify Heroku application deployment
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "staging ${{ inputs.environment }}",
              "blocks": [
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "staging ${{ inputs.environment }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEVOPS_STAGING_WEBHOOK_URL }}
      - if: inputs.enableNotification && (inputs.environment == 'production')
        name: Notify Heroku application deployment
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "production ${{ inputs.environment }}",
              "blocks": [
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "production ${{ inputs.environment }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEVOPS_PRODUCTION_WEBHOOK_URL }}
      - if: inputs.enableNotification && (inputs.environment != 'staging') && (inputs.environment != 'production')
        name: Notify Heroku application deployment
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "develop ${{ inputs.environment }}",
              "blocks": [
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "develop ${{ inputs.environment }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEVOPS_WEBHOOK_URL }}