name: tag to issue

on:
  issue_comment:
    types: 
      - created

jobs:
  promote_pipeline:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if more than one promotion pipeline exists
        run: |
          issues=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{github.token}}" \
          https://api.github.com/repos/${{github.repository}}/issues?labels=promotion-pipeline&state=open)
          issues_numbers=$(echo ${issues} | jq '.[].number')
          length_issues=$(wc -w <<< "$issues_numbers")
          if [[ "$length_issues" == "0" ]];
          then
            echo "Comment from another issue not related to promotion pipeline"
            exit 0;
          elif [[ "$length_issues" == "1" ]] && [[ "$issues_numbers" == "${{ github.event.issue.number }}" ]];
          then
            echo "Ready to promote artifacts"
          else
            echo "Two or more promotion pipelines are open. Only one promotion pipelines should exists"
            for i in $issues_numbers;
            do
              echo "https://github.com/${{github.repository}}/issues/$i"
            done
            exit 1;
          fi
      - name: $github
        run:   echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Check comment from approver
        run: |
          # Get comments
          echo ${{ github.event.issue }}
          # curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{github.token}}" \
          # -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{github.repository}}/issues/comments/${{ github.event.issue.comment_id }}

          # # Get the issue
          # curl -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{github.token}}" \
          # https://api.github.com/repos/${{github.repository}}/issues/${{ github.event.issue.number }}