name: Deploy to Develop

on:
  workflow_call:
    inputs:
      pipeline_workflow_ref:
        required: false
        type: string
        default: main
      SENTRY_TOKEN:
        required: true
        type: string
      DASHBOARD_SENTRY_DSN:
        required: true
        type: string
      PAY_SENTRY_DSN:
        required: true
        type: string

concurrency:
  group: dashboard-pipelines-deploy-develop
  cancel-in-progress: false

jobs:
  deploy-develop:
    name: Deploy Develop
    uses: ./.github/workflows/deploy-env.yml
    with:
      pipeline_workflow_ref: ${{ inputs.pipeline_workflow_ref }}
      SENTRY_ENVIRONMENT: DEVELOP
      SENTRY_TOKEN: ${{ inputs.SENTRY_TOKEN }}
      DASHBOARD_SENTRY_DSN: ${{ inputs.DASHBOARD_SENTRY_DSN }}
      PAY_SENTRY_DSN: ${{ inputs.PAY_SENTRY_DSN }}
    secrets: inherit