name: lgtm
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.4
      - uses: micnncim/action-lgtm-reaction@v0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
