name: test push

on:
  push:
    branches:
      - develop

concurrency:
  group: develop-deploy-concurrency-group
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Develop
    uses: ./.github/workflows/deploy-develop.yml
    with:
      pipeline_workflow_ref: v1.0.3
      SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
      DASHBOARD_SENTRY_DSN: ${{ secrets.DASHBOARD_SENTRY_DSN }}
      PAY_SENTRY_DSN: ${{ secrets.PAY_SENTRY_DSN }}
    secrets: inherit
