name: test push

on:
  push:
    branches:
      - develop

concurrency:
  group: develop-deploy-concurrency-group
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          echo "hola"
  deploy:
    name: Deploy Develop
    uses: ./.github/workflows/deploy-develop.yml
    with:
      pipeline_workflow_ref: v1.0.3
      SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
      DASHBOARD_SENTRY_DSN: ${{ secrets.DASHBOARD_SENTRY_DSN }}
      PAY_SENTRY_DSN: ${{ secrets.PAY_SENTRY_DSN }}
    secrets: inherit
