name: Heroku - Promote release to production

on:
  push:
    tags:
      - test

jobs:
  start_promotion_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue with pipeline details
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{github.token}}" \
          https://api.github.com/repos/${{github.repository}}/issues \
          -d '{"title":"Artifact Promotion","body":"New promotion pipeline created for tag ${{github.ref}}","assignees":["fergo2910"],"labels":["promotion-pipeline"]}'