name: release-branch-deployment

on:
  workflow_dispatch

jobs:
  create_release_branch:
    runs-on: ubuntu-latest
    outputs:
      release_branch_name: ${{ steps.create_release_branch.outputs.release_branch_name }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: checkout-develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - id: create_release_branch
        name: Create a release branch
        run: |
          release_branch_name="release/"$(date -d "-7 hours" +"%Y-%m-%d/%H-%M-%S")
          git checkout -b $release_branch_name
          git push origin $release_branch_name
          echo ::set-output name=release_branch_name::$release_branch_name
  release_deployment_staging:
    