name: release-branch-deployment

on:
  workflow_dispatch

jobs:
  release-deployment-staging:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - id: create-release-branch
        name: Create a release branch
        run: |
          release_branch_name="release/"$(date -d "-7 hours" +"%Y-%m-%d/%H-%M-%S")
          git checkout -b $release_branch_name
          git push origin $release_branch_name
          echo ::set-output name=release_branch_name::$release_branch_name
      - id: deployment-of-dashboard-staging
        uses: ./.github/actions/deploy-heroku-app
        with:
          herokuApplication: staging-tmp
          checkoutBranch: ${{ steps.create-release-branch.outputs.release_branch_name }}