on:
  push:
    tags:
      - hotfix-20**
      - release/20**
    branches:
      - release/20**

jobs:
  tags:
    runs-on: ubuntu-latest
    outputs:
      slack_webhook_url: ${{ steps.promote.outputs.slack_webhook_url }}
    steps:
      - name: test
        id: promote
        run: |
          echo "slack_webhook_url=${{ secrets.SLACK_1 }}" >> $GITHUB_OUTPUT

  msg:
    needs: [tags]
    runs-on: ubuntu-latest
    steps:
      - name: slack
        run: |
          slack_payload=$(echo "{\"text\":\":steam_locomotive: CICD a deployment promotion has finished, deployment finished to b AWS environment. Commit: *c* :steam_locomotive: \"}")
          curl -X POST -H 'Content-type: application/json' --data "$slack_payload" ${{ needs.tags.outputs.slack_webhook_url }}
