name: release-branch-deployment

on:
  workflow_dispatch

jobs:
  create_release_branch:
    name: Create Release Branch
    runs-on: ubuntu-latest
    outputs:
      release_branch_name: ${{ steps.create_release_branch.outputs.release_branch_name }}
    steps:
      - id: checkout-develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - id: create_release_branch
        name: Create a release branch
        run: |
          release_branch_name="release/"$(date -d "-7 hours" +"%Y-%m-%d/%H-%M-%S")
          git checkout -b $release_branch_name
          git push origin $release_branch_name
          echo ::set-output name=release_branch_name::$release_branch_name
  release_deployment_staging:
    needs: [create_release_branch]
    name: Deploy to Heroku
    uses: ./.github/workflows/deploy-heroku-app.yml
    secrets: inherit
    with:
      herokuApplication: staging-tmp
      checkoutBranch: ${{ needs.create_release_branch.outputs.release_branch_name }}
    secrets:
      input_slack_webhook_url: ${{ secrets.SLACK_DEVOPS_STAGING_WEBHOOK_URL }}
  # promote_release_to_production:
  #   needs: [release_deployment_staging]
  #   name: Promote release to production
  #   uses: ./.github/workflows/deploy-heroku-promote.yml
  #   secrets: inherit
  #   with:
  #     herokuApplication: staging-tmp
  #     herokuPipeline: devops-tmp-pipeline
  #     checkoutBranch: ${{ needs.create_release_branch.outputs.release_branch_name }}