on:
  push:
    tags:
      - hotfix-20**
      - release/20**
    branches:
      - release/20**

jobs:
  tags:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "test"